version: '3'

networks:
  bubble:
    driver: bridge

volumes:
  acme.json: {}

services:
  traefik:
    build:
      context: ./traefik
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme.json:/acme.json
#    restart: on-failure
    networks:
      - bubble

#  redis:
#    image: redis:3.2
#    container_name: bubble_redis
##    restart: on-failure
#    ports:
#    - "0.0.0.0:6378:6379"
#    networks:
#      - bubble
