defaultEntryPoints = ["http",]

[log]
    level='DEBUG'

[accessLog]
 #   format="json"

# Entrypoints, http and https
[entryPoints]
  [entryPoints.http]
    address = ":80"


[api]
    dashboard = true
    insecure = true
    debug = true

[providers]
  providersThrottleDuration = 10
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "bubble"
    useBindPortIP = True




